version: "3.7"

services:

  db:
    container_name: db
    build:
      context: db
      dockerfile: db.dockerfile
    volumes:
      - db_volume:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: back.dockerfile
    expose:
      - 5000
    volumes:
      - ./backend:/www
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_volume: